### ISSUE TITLE
Documentation in Structured Format

### ISSUE THREAD

**Issue by mlajkim** [ajktown/docs#10]
# Background
Currently, our documentation repository holds valuable information, but lacks a structured format. Our aim is to organize every file according to the documentation standards utilized by major IT corporations such as Google and Amazon.

## TODOs
- [x] Find the standard of Google Level (AWS, Git etc)
  - Almost decided to use the gitlab standard
  - ![image](https://github.com/ajktown/docs/assets/53258958/f64d0f96-6197-44f8-9941-276bc18f606d)
  - Source: https://docs.gitlab.com/ee/development/documentation/site_architecture/folder_structure.html
- [x] Make sure that the industry standard is credited in `README.md`
- [x] Decide whether to follow all the standards of GitLab defines
