### ISSUE TITLE
GitHub Labels Standard

### ISSUE THREAD

**Issue by mlajkim** [ajktown/docs#30]
# Background
I want to set the standard 

## TODOs
- [ ] Set default labels with DEFAULT colors
- [ ] How to have the defaults within the AJK Town with Clear Description!
- [ ] How to enforce setting labels
- [ ] Apply to https://github.com/AthenZ/k8s-athenz-sia
  - I am the owner of this product.
